#ifndef __eosConfig__
#define __eosConfig__


#define USE_LEDS_LED1
#define USE_LEDS_LED2
#if defined(HARDWARE_PIC32_USB_STARTER_KIT_I)
	#define USE_LEDS_LED3
#endif

#define USE_SWITCHES_SW1
#if defined(HARDWARE_PIC32_USB_STARTER_KIT_I)
#define USE_SWITCHES_SW2
#endif
#if defined(HARDWARE_PIC32_USB_STARTER_KIT_I)
#define USE_SWITCHES_SW3
#endif


#define AXIS_MOTOR_X_STEP_PORT         HAL_GPIO_PORT_A
#define AXIS_MOTOR_X_STEP_PIN          HAL_GPIO_PIN_12
#define AXIS_MOTOR_X_DIRECTION_PORT    HAL_GPIO_PORT_A
#define AXIS_MOTOR_X_DIRECTION_PIN     HAL_GPIO_PIN_12
#define AXIS_MOTOR_X_ENABLE_PORT       HAL_GPIO_PORT_A
#define AXIS_MOTOR_X_ENABLE_PIN        HAL_GPIO_PIN_12

#define AXIS_MOTOR_Y_STEP_PORT         HAL_GPIO_PORT_D
#define AXIS_MOTOR_Y_STEP_PIN          HAL_GPIO_PIN_2
#define AXIS_MOTOR_Y_DIRECTION_PORT    HAL_GPIO_PORT_A
#define AXIS_MOTOR_Y_DIRECTION_PIN     HAL_GPIO_PIN_12
#define AXIS_MOTOR_Y_ENABLE_PORT       HAL_GPIO_PORT_A
#define AXIS_MOTOR_Y_ENABLE_PIN        HAL_GPIO_PIN_12

#define AXIS_MOTOR_Z_STEP_PORT         HAL_GPIO_PORT_D
#define AXIS_MOTOR_Z_STEP_PIN          HAL_GPIO_PIN_2
#define AXIS_MOTOR_Z_DIRECTION_PORT    HAL_GPIO_PORT_A
#define AXIS_MOTOR_Z_DIRECTION_PIN     HAL_GPIO_PIN_12
#define AXIS_MOTOR_Z_ENABLE_PORT       HAL_GPIO_PORT_A
#define AXIS_MOTOR_Z_ENABLE_PIN        HAL_GPIO_PIN_12


#include "board/board.h"


#endif // __eosConfig__
